/**
 * ============================================================================
 * ERROR HANDLING - LESSON 455: The error.js Reserved File
 * ============================================================================
 *
 * LESSON 455 - HANDLING ERRORS WITH error.js
 *
 * INSTRUCTOR QUOTE:
 * "Now this loading.JS file, even though we're not using it anymore here
 * is not the only other special file you can add in that app folder in your
 * next project, because besides loading and page and layout, we, for example,
 * can also add an error.js file, which will handle potential errors that
 * might be generated by your pages and components."
 *
 * RESERVED FILES IN NEXT.JS APP ROUTER:
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  FILE NAME        │  PURPOSE                                            │
 * │  ─────────────────│─────────────────────────────────────────────────────│
 * │  page.js          │  The main page component for a route                │
 * │  layout.js        │  Shared UI that wraps pages and nested layouts      │
 * │  loading.js       │  Loading UI shown while page/data is loading        │
 * │  error.js         │  Error UI shown when an error occurs ← THIS FILE    │
 * │  not-found.js     │  UI shown for 404 errors                            │
 * │  template.js      │  Like layout, but re-mounts on navigation           │
 * │  route.js         │  API endpoint (Route Handler)                       │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * ============================================================================
 * ERROR HANDLING SCOPE
 * ============================================================================
 *
 * INSTRUCTOR QUOTE:
 * "Though, it'll only handle errors that occur in the page that sits in the
 * same folder as this error.js file or any nested page or layout. Therefore,
 * you could of course also add this on the root level of your application to
 * catch any error that's cost anywhere in any of your pages."
 *
 * ERROR BOUNDARY SCOPE:
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  LOCATION OF error.js    │  CATCHES ERRORS FROM                         │
 * │  ────────────────────────│──────────────────────────────────────────────│
 * │  app/error.js            │  Any page/component in the entire app        │
 * │  app/meals/error.js      │  Only /meals and nested routes ← THIS FILE   │
 * │  app/meals/[slug]/error.js │  Only /meals/[slug] dynamic routes         │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * INSTRUCTOR QUOTE:
 * "Here, I'll go down one level so that I don't replace the entire site
 * with my error screen, but instead only a part of that site."
 *
 * ============================================================================
 * WHY ERROR.JS MUST BE A CLIENT COMPONENT
 * ============================================================================
 *
 * INSTRUCTOR QUOTE:
 * "You'll get another error where we learn that error.JS must be a client
 * component. And indeed that's the case. This error component that's stored
 * in an error.JS file must be a client component simply because NextJS
 * basically ensures that you can catch any errors with that component,
 * including errors that happen on the client side so after the pages were
 * rendered on the server. That's why this directive must be added here."
 *
 * WHY CLIENT COMPONENT IS REQUIRED:
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  ✓ Catches server-side rendering errors                                 │
 * │  ✓ Catches client-side runtime errors                                   │
 * │  ✓ Can use React's Error Boundary under the hood                        │
 * │  ✓ Can provide interactive recovery options (retry buttons, etc.)       │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * ============================================================================
 */
'use client';

/**
 * ============================================================================
 * ERROR PAGE COMPONENT
 * ============================================================================
 *
 * INSTRUCTOR QUOTE:
 * "And in that file, you then set up a component that will be rendered by
 * NextJS whenever an error occurs."
 *
 * PROPS PROVIDED BY NEXT.JS:
 *
 * INSTRUCTOR QUOTE:
 * "For that to learn more about this error, we can actually use some props
 * here in this error page component because when setting up such a component
 * in such a error or JS file, NextJS will pass some props to that component.
 * Most importantly, it will provide an error prop, which can contain more
 * details about the error."
 *
 * PROPS STRUCTURE:
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  { error, reset }                                                       │
 * │                                                                          │
 * │  error: Error object with details about what went wrong                 │
 * │         - error.message (hidden in production for security)             │
 * │         - error.digest (unique error identifier)                        │
 * │                                                                          │
 * │  reset: Function to attempt re-rendering the error boundary's contents  │
 * │         (useful for "Try again" buttons)                                │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * SECURITY NOTE:
 *
 * INSTRUCTOR QUOTE:
 * "Now, the actual error message will actually be hidden by NextJS so that
 * you can't accidentally expose any information that shouldn't be exposed
 * to your end users."
 *
 * @param {Object} props - Props provided by Next.js
 * @param {Error} props.error - The error object (message hidden in production)
 * @returns {JSX.Element} Error UI component
 */
export default function Error({ error }) {
  /**
   * ERROR UI RENDERING
   *
   * INSTRUCTOR QUOTE:
   * "And here, I'll then simply output some main element with a class name
   * of error and I'm setting this class name like this because that's not
   * actually a class I prepared in this global CSS file, which was part of
   * the starting project. And we're importing that globally, not as a CSS
   * module. They offer those classes from that file can be used just like
   * this."
   *
   * NOTE: The `error` class comes from app/globals.css which is imported
   * globally in the root layout, not as a CSS Module. This allows us to
   * use the class name as a plain string without importing.
   *
   * STYLING FROM globals.css:
   * ┌─────────────────────────────────────────────────────────────────────┐
   * │  .error {                                                           │
   * │    margin-top: 5rem;                                                │
   * │    text-align: center;                                              │
   * │  }                                                                  │
   * │                                                                      │
   * │  .error h1 {                                                        │
   * │    font-size: 5rem;                                                 │
   * │    font-weight: 900;                                                │
   * │    color: #262626;                                                  │
   * │    text-transform: uppercase;                                       │
   * │  }                                                                  │
   * │                                                                      │
   * │  .error p {                                                         │
   * │    font-size: 1.5rem;                                               │
   * │    font-weight: 500;                                                │
   * │    color: #ddd8d8;                                                  │
   * │  }                                                                  │
   * └─────────────────────────────────────────────────────────────────────┘
   */
  return (
    <main className="error">
      <h1>An error occurred!</h1>
      {/**
       * GENERIC ERROR MESSAGE
       *
       * INSTRUCTOR QUOTE:
       * "But if your error would be an object that also contains some error
       * code or anything like that, you could use that here in this component
       * to show a more fine tuned error message. Here, I'll simply output a
       * generic message and say, failed to fetch meal data. Please try again
       * later."
       *
       * WHY A GENERIC MESSAGE?
       * - error.message is hidden in production for security
       * - Prevents leaking sensitive system information to users
       * - Provides consistent, user-friendly messaging
       *
       * ADVANCED: For more specific error handling, you could:
       * - Check error.digest for specific error types
       * - Use error codes in your thrown errors
       * - Provide different messages based on error type
       */}
      <p>Failed to fetch meal data. Please try again later.</p>
    </main>
  );
}

/**
 * ============================================================================
 * LESSON 455 - ERROR HANDLING SUMMARY
 * ============================================================================
 *
 * WHAT WE LEARNED:
 *
 * 1. error.js IS ANOTHER RESERVED FILE NAME
 *
 *    INSTRUCTOR QUOTE:
 *    "Besides loading and page and layout, we, for example, can also add an
 *    error.js file, which will handle potential errors that might be generated
 *    by your pages and components."
 *
 * 2. ERROR HANDLING IS SCOPED TO FOLDER LEVEL
 *    - Catches errors in same folder and nested routes
 *    - Place at root level for app-wide error handling
 *    - Place in specific folders for granular control
 *
 * 3. MUST BE A CLIENT COMPONENT ('use client')
 *    - Required to catch both server and client errors
 *    - Uses React Error Boundary under the hood
 *
 * 4. RECEIVES error AND reset PROPS
 *    - error: Contains error details (message hidden in production)
 *    - reset: Function to retry rendering (for "Try Again" buttons)
 *
 * 5. ERROR MESSAGES ARE HIDDEN IN PRODUCTION
 *    - Prevents exposing sensitive information to users
 *    - Use error codes for specific error handling
 *
 * DEVELOPMENT vs PRODUCTION ERROR SCREENS:
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  DEVELOPMENT:                                                           │
 * │  - Shows detailed error stack trace                                     │
 * │  - Displays full error message                                          │
 * │  - Helpful for debugging                                                │
 * │                                                                          │
 * │  PRODUCTION:                                                            │
 * │  - Shows your custom error.js component                                 │
 * │  - Error details hidden for security                                    │
 * │  - User-friendly messaging                                              │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * INSTRUCTOR QUOTE:
 * "The error screen we see here is just a development version of this error
 * screen. In production, this would look differently. We see this screen
 * during development so that it's easier for us as a developer to find and
 * fix the error."
 *
 * TO TEST ERROR HANDLING:
 * 1. Go to lib/meals.js
 * 2. Uncomment: throw new Error('Loading meals failed.');
 * 3. Reload the /meals page
 * 4. See the custom error page
 * 5. Comment the line back out when done testing
 *
 * ============================================================================
 */
