/**
 * ============================================================================
 * App.tsx — LESSON 591
 * ============================================================================
 *
 * REACT + TYPESCRIPT: THE MAIN APPLICATION COMPONENT
 *
 * This file is the root component of a React project created with
 * Create React App using the TypeScript template. It looks nearly
 * identical to the App.js file from a standard (non-TypeScript)
 * CRA project — the React code itself does not change.
 *
 * FILE EXTENSION — .tsx vs .ts vs .js:
 *
 *   .js   — standard JavaScript (used throughout this course so far)
 *   .ts   — TypeScript WITHOUT JSX (e.g., utility files, pure logic)
 *   .tsx  — TypeScript WITH JSX (any file that contains JSX markup)
 *
 * The "x" in .tsx signals to the TypeScript compiler that this file
 * contains JSX syntax. Without the "x", the compiler would not know
 * how to parse the angle-bracket HTML-like markup and would report
 * errors. As a rule: if a file returns or contains JSX, use .tsx;
 * if it contains only plain TypeScript logic, use .ts.
 *
 * WHY THE CODE LOOKS THE SAME:
 *
 * TypeScript adds type annotations ON TOP of JavaScript — it does
 * not replace the React APIs or component patterns. A functional
 * component is still a function that returns JSX. Props, state,
 * hooks, and events all work exactly as before. The difference is
 * that TypeScript can now check the types of props, state values,
 * event objects, and more — catching mistakes at compile time
 * rather than at runtime.
 *
 * ============================================================================
 */

import React from 'react';
import logo from './logo.svg';
import './App.css';

// This is the same default App component generated by Create React App.
// The only visible difference from a JavaScript CRA project is the file
// extension: App.tsx instead of App.js. The component code itself —
// the function signature, the JSX return, the imports — is unchanged.
function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
