/**
 * ============================================================================
 * ERROR PAGE COMPONENT (Lesson 351)
 * ============================================================================
 *
 * WHY DO WE NEED AN ERROR PAGE? (Lesson 351):
 * ===========================================
 * INSTRUCTOR QUOTE:
 * "Now of course, it's not unlikely, that over time visitors might accidentally,
 * or, due to erroneous links provided by us, visit pages that they shouldn't
 * visit, that simply don't exist. And therefore, you might want to prepare a
 * default error page that's shown in situations like this."
 *
 * DEFAULT BEHAVIOR WITHOUT ERROR PAGE (Lesson 351):
 * =================================================
 * INSTRUCTOR QUOTE:
 * "Now, you might remember that earlier, when we visited a route like our
 * domain slash abc, we got this error page here, this default error message,
 * which is actually generated by the react-router-dom package."
 *
 * The default error page from react-router-dom is not user-friendly.
 * Creating a custom error page provides a better user experience.
 *
 * ============================================================================
 * HOW ERROR PAGES WORK WITH ROUTING (Lesson 351)
 * ============================================================================
 *
 * ERROR BUBBLING (Lesson 351):
 * ============================
 * INSTRUCTOR QUOTE:
 * "When we enter a URL that doesn't exist, the react-router-dom package will
 * generate an error, and that error will automatically bubble up to our root
 * route definition. So to the route that is defined for path slash nothing."
 *
 * Error propagation flow:
 * 1. User visits /some-invalid-path
 * 2. React Router can't find a matching route
 * 3. Error is generated automatically
 * 4. Error bubbles up to the nearest route with an errorElement
 * 5. The errorElement is rendered instead of the normal element
 *
 * VISUALIZATION:
 * ==============
 * User visits: /abc (doesn't exist)
 *
 * ┌─────────────────────────────────────────┐
 * │     Route: path='/'                     │
 * │     element: <RootLayout />             │
 * │     errorElement: <ErrorPage /> ◄───────┼── Error bubbles up here!
 * │     children: [                         │
 * │       { path: '/', ... }                │
 * │       { path: '/products', ... }        │
 * │     ]                                   │
 * │                     ▲                   │
 * │                     │                   │
 * │         No match for '/abc'             │
 * │         Error generated!                │
 * └─────────────────────────────────────────┘
 *
 * RESULT: <ErrorPage /> is rendered instead of <RootLayout />
 *
 * ============================================================================
 * IMPORTANT NOTE ABOUT LAYOUT (Lesson 351)
 * ============================================================================
 *
 * When an error occurs, the errorElement REPLACES the normal element.
 * This means RootLayout (with MainNavigation) is NOT rendered!
 *
 * Therefore, if we want navigation on the error page, we must include
 * MainNavigation directly in the ErrorPage component.
 *
 * INSTRUCTOR QUOTE:
 * "We could, for example, include the main navigation here if you want to,
 * and then below that have our main content where we say an error occurred,
 * could not find this page."
 */

import MainNavigation from '../components/MainNavigation';

/**
 * ERROR PAGE COMPONENT:
 * =====================
 * INSTRUCTOR QUOTE (Lesson 351):
 * "To do that we could add a new page here called error page, like that,
 * and in here we could return our error page content."
 *
 * This component:
 * 1. Includes MainNavigation for consistent user experience
 * 2. Displays a friendly error message
 * 3. Allows users to navigate back to valid pages
 */
function ErrorPage() {
  return (
    <>
      {/**
       * MAIN NAVIGATION ON ERROR PAGE (Lesson 351):
       * ===========================================
       * INSTRUCTOR QUOTE:
       * "We could, for example, include the main navigation here if you want to"
       *
       * By including MainNavigation, users can easily navigate away
       * from the error page to a valid page.
       */}
      <MainNavigation />

      {/**
       * ERROR CONTENT (Lesson 351):
       * ===========================
       * INSTRUCTOR QUOTE:
       * "And then below that have our main content where we say an error
       * occurred, could not find this page."
       *
       * The <main> element uses global styling from index.css.
       * This was moved from Root.module.css to ensure consistent
       * styling on both the normal layout AND the error page.
       */}
      <main>
        <h1>An error occurred!</h1>
        <p>Could not find this page!</p>
      </main>
    </>
  );
}

export default ErrorPage;
