/**
 * ============================================================================
 * _app.js - LESSON 479: NextJS Project Structure
 * ============================================================================
 *
 * This is a special file in the /pages folder that wraps ALL pages.
 *
 * ============================================================================
 * 🎓 LESSON 479: PROJECT STRUCTURE
 * ============================================================================
 *
 * From the instructor:
 * "So we did create that NextJS project here in the terminal with NPX
 * create-next-app, and that gave us a folder which looks like this,
 * which has this kind of content."
 *
 * ============================================================================
 * NPM INSTALL REQUIREMENT
 * ============================================================================
 *
 * From the instructor:
 * "If you do download the attached snapshot though, there is one extra step
 * you need to go through. You need to open the terminal, and you can use
 * the one built into Visual Studio Code, which is your default terminal...
 * And here you then need to run npm install if you use that attached snapshot."
 *
 * WHY NPM INSTALL IS NEEDED:
 *
 * From the instructor:
 * "Because that will then install all the dependencies of this project as
 * defined here in package.json, and store them and their dependencies in
 * the node modules folder. So that's also a folder in which will never work."
 *
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  SETUP STEPS FOR ATTACHED SNAPSHOTS                                     │
 * │                                                                          │
 * │  1. Download and extract the project snapshot                            │
 * │  2. Open terminal in project folder (VS Code terminal works great)      │
 * │  3. Run: npm install                                                     │
 * │  4. Dependencies installed to /node_modules                              │
 * │  5. Ready to run: npm run dev                                            │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * ============================================================================
 * THE NODE_MODULES FOLDER
 * ============================================================================
 *
 * From the instructor:
 * "So that's also a folder in which will never work."
 *
 * The /node_modules folder:
 * • Contains all installed dependencies
 * • Generated by npm install
 * • Should NOT be committed to version control (.gitignore)
 * • Can be regenerated from package.json anytime
 *
 * ============================================================================
 * WHAT _app.js DOES
 * ============================================================================
 *
 * _app.js is the root component that wraps every page in your application.
 * It's used for:
 *
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  1. Importing global CSS (like globals.css)                              │
 * │  2. Persisting layout between page navigations                           │
 * │  3. Adding global state providers (Redux, Context, etc.)                 │
 * │  4. Custom error handling                                                │
 * │  5. Injecting additional data into pages                                 │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * ============================================================================
 */

/**
 * Global CSS Import
 *
 * Global CSS can ONLY be imported in _app.js (not in individual pages).
 * This ensures consistent styling across all pages.
 */
import '../styles/globals.css'

/**
 * MyApp - Root Application Component
 *
 * @param {Object} props
 * @param {React.ComponentType} props.Component - The active page component
 * @param {Object} props.pageProps - Props from getServerSideProps/getStaticProps
 *
 * Every page in your app is rendered through this component.
 * When you navigate from / to /about, Component changes accordingly.
 */
function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default MyApp
